# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservicepb\"\x94\x01\n\x04\x43\x65ll\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x05 \x01(\x0cH\x00\x12\x11\n\x07is_null\x18\x06 \x01(\x08H\x00\x42\x07\n\x05value\"9\n\x06\x43olumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0bis_nullable\x18\x03 \x01(\x08\"%\n\x03Row\x12\x1e\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x0f.servicepb.Cell\";\n\rQueryMetadata\x12\x17\n\x0fquery_generated\x18\x01 \x01(\t\x12\x11\n\trow_count\x18\x02 \x01(\x03\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa8\x01\n\rQueryResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\"\n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x11.servicepb.Column\x12\x1c\n\x04rows\x18\x04 \x03(\x0b\x32\x0e.servicepb.Row\x12*\n\x08metadata\x18\x05 \x01(\x0b\x32\x18.servicepb.QueryMetadata2N\n\x0eNLToSQLService\x12<\n\x07QueryDB\x12\x17.servicepb.QueryRequest\x1a\x18.servicepb.QueryResponseB3Z1github.com/ManoVikram/NL-To-SQL-With-AI/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/ManoVikram/NL-To-SQL-With-AI/api/proto'
  _globals['_CELL']._serialized_start=29
  _globals['_CELL']._serialized_end=177
  _globals['_COLUMN']._serialized_start=179
  _globals['_COLUMN']._serialized_end=236
  _globals['_ROW']._serialized_start=238
  _globals['_ROW']._serialized_end=275
  _globals['_QUERYMETADATA']._serialized_start=277
  _globals['_QUERYMETADATA']._serialized_end=336
  _globals['_QUERYREQUEST']._serialized_start=338
  _globals['_QUERYREQUEST']._serialized_end=367
  _globals['_QUERYRESPONSE']._serialized_start=370
  _globals['_QUERYRESPONSE']._serialized_end=538
  _globals['_NLTOSQLSERVICE']._serialized_start=540
  _globals['_NLTOSQLSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
