// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NLToSQLService_QueryDB_FullMethodName = "/servicepb.NLToSQLService/QueryDB"
)

// NLToSQLServiceClient is the client API for NLToSQLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NLToSQLServiceClient interface {
	QueryDB(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type nLToSQLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNLToSQLServiceClient(cc grpc.ClientConnInterface) NLToSQLServiceClient {
	return &nLToSQLServiceClient{cc}
}

func (c *nLToSQLServiceClient) QueryDB(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NLToSQLService_QueryDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NLToSQLServiceServer is the server API for NLToSQLService service.
// All implementations must embed UnimplementedNLToSQLServiceServer
// for forward compatibility.
type NLToSQLServiceServer interface {
	QueryDB(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedNLToSQLServiceServer()
}

// UnimplementedNLToSQLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNLToSQLServiceServer struct{}

func (UnimplementedNLToSQLServiceServer) QueryDB(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDB not implemented")
}
func (UnimplementedNLToSQLServiceServer) mustEmbedUnimplementedNLToSQLServiceServer() {}
func (UnimplementedNLToSQLServiceServer) testEmbeddedByValue()                        {}

// UnsafeNLToSQLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NLToSQLServiceServer will
// result in compilation errors.
type UnsafeNLToSQLServiceServer interface {
	mustEmbedUnimplementedNLToSQLServiceServer()
}

func RegisterNLToSQLServiceServer(s grpc.ServiceRegistrar, srv NLToSQLServiceServer) {
	// If the following call panics, it indicates UnimplementedNLToSQLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NLToSQLService_ServiceDesc, srv)
}

func _NLToSQLService_QueryDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLToSQLServiceServer).QueryDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLToSQLService_QueryDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLToSQLServiceServer).QueryDB(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NLToSQLService_ServiceDesc is the grpc.ServiceDesc for NLToSQLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NLToSQLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.NLToSQLService",
	HandlerType: (*NLToSQLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDB",
			Handler:    _NLToSQLService_QueryDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
